config/routes.rb
Rails.application.routes.draw do
  #get 'reviews/index'
  #get 'reviews/show'
  #get 'reviews/new'
  #get 'reviews/edit'
  #get 'restaurants/index'
  #get 'restaurants/show'
  #get 'restaurants/edit'
  #get 'restaurants/new'

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
has_many :reviews, dependent: :destroy
validates :name, :address, :category, presence: true

end


# t.string :name
#       t.string :address
#       t.integer :phonenumber
#       t.string :category

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end
  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end


  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address,:category, :phone_number)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
   def index
    @reviews = Review.all
  end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
    redirect_to restaurants_path
    else
    render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end
  def update
    @review = Review.find(params[:id])
    @review.update(review_params)
    redirect_to reviews_path
  end

  private
  def review_params
    params.require(:review).permit(:content,:rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h1>restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

<%= simple_form_for [@restaurant] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit "edit this restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/index.html.erb
<div class="container">

<h1> All restaurants</h1>
<% @restaurants.each do |restaurant| %>
<p><%= link_to restaurant.name, restaurant_path(restaurant) %> </p>
<%= link_to "edit a restaurant", edit_restaurant_path(restaurant) %>
<%= link_to "add a review", new_restaurant_review_path(restaurant) %>
<% end %>

<%= link_to "add a restaurant", new_restaurant_path %>


</div>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>

<%= simple_form_for [@restaurant] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit "add a restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<h1>Restaurant#show</h1>
<p>Find me in app/views/restaurant/show.html.erb</p>
<%= @restaurant.name %>
<%= @restaurant.address %>
<%= @restaurant.category %>
<%= @restaurant.phone_number %>
<% @restaurant.reviews.each do |review| %>
  <%= review.content %> -- <%=review.rating  %>
  <% end %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>


<%= simple_form_for [@restaurant] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "edit this rating", class: "btn btn-primary" %>
<% end %>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

<% @reviews.each do |review| %>
<p><%= review.content "--" review.rating %> <%= link_to "edit a review", edit_review_path(review) </p>
<%= link_to "edit a review", edit_review_path(review) %>
<% end %>

<%= link_to "add a review", new_restaurant_review_path %>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "add a rating", class: "btn btn-primary" %>
<% end %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

<p>Find me in app/views/reviews/index.html.erb</p>

<% @reviews.each do |review| %>
<p><%= review.content "--" review.rating %> <%= link_to "edit a review", edit_review_path(review) </p>
<%= link_to "edit a review", edit_review_path(review) %>
<% end %>

<%= link_to "add a review", new_restaurant_review_path %>